/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package jpa;

import java.util.Arrays;
import java.util.List;

//import java.util.List;

import javax.persistence.EntityManager;
import javax.persistence.EntityManagerFactory;
import javax.persistence.Persistence;
//import javax.persistence.Query;

public class Library {
	
   public static void main(String[] args) {
	   Smartphone sm1 = new Smartphone();
	   sm1.setSm_id(10001);
	   sm1.setSm_name("Realme");
	   
	   Smartphone sm2 = new Smartphone();
	   sm2.setSm_id(10002);
	   sm2.setSm_name("Xiaomi");
	   
	   Books bk1 = new Books();
	   bk1.setBid(1001);
	   bk1.setBname("Algorithms");
	   
	   Books bk2 = new Books();
	   bk2.setBid(1002);
	   bk2.setBname("Data Structures");
	   
	   Laptop lp1 = new Laptop();
	   lp1.setLid(101);
	   lp1.setLname("Dell");
	   
	   Laptop lp2 = new Laptop();
	   lp2.setLid(102);
	   lp2.setLname("HP");
	   
	   Student st1 = new Student();
	   st1.setSid(1);
	   st1.setSname("Hemang");
	   
	   Student st2 = new Student();
	   st2.setSid(2);
	   st2.setSname("Jaydeep");
	   
	   List<Books> bok = Arrays.asList(bk1,bk2);
	   List<Laptop> lap = Arrays.asList(lp1,lp2);
	   List<Student> std = Arrays.asList(st1, st2);
	   
	   st1.setSmartphone(sm1);
	   sm1.setStudent(st1);
	   st1.setBooks(bok);
	   st1.setLaptop(lap);
	   lp1.setStudent(std);
	   
	   st2.setSmartphone(sm2);
	   sm2.setStudent(st2);
	   st2.setBooks(bok);
	   st2.setLaptop(lap);
	   lp2.setStudent(std);
	   
	   bk1.setStudent(st1);
	   bk2.setStudent(st2);
	   
	   EntityManagerFactory emf = Persistence.createEntityManagerFactory("stu_details");
	   EntityManager em = emf.createEntityManager();
	   em.getTransaction().begin();
	   
	   em.persist(st1);
	   em.persist(sm1);
	   em.persist(bk1);
	   em.persist(lp1);
	   
	   em.persist(st2);
	   em.persist(sm2);
	   em.persist(bk2);
	   em.persist(lp2);
	   
// Find operation of JPA
// 	   st = em.find(Student.class, 1);
	 
// Update operation of JPA
//	   st.setHobby("Programming");
	   
// Remove operation of JPA
//     em.remove(st);
	   
// Add to database 
//	   em.persist(st);

// Query 
//	   Query query = em.createQuery("from Student");
//	   List<Student> s = query.getResultList();
//	   s.forEach(System.out::println);
//	   
	   em.getTransaction().commit();
	  
	   em.close();
	   emf.close();
    }
}
