/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package EmbeddableObject;

import org.hibernate.Session;
import org.hibernate.SessionFactory;
import org.hibernate.cfg.Configuration;

public class Library {
    public static void main(String[] args) {
    	
    	StudName sn = new StudName();
    	sn.setFname("Koshiyar");
    	sn.setMname("Hemang");
    	sn.setLname("Bharatbhai");
    	
    	Student st = new Student();
    	st.setRollno(1);
    	st.setName(sn);
    	st.setHobby("Cricket");
    	
    	Configuration con = new Configuration().configure().addAnnotatedClass(Student.class);
    	SessionFactory sf = con.buildSessionFactory();
    	Session session = sf.openSession();
    	session.beginTransaction();
    	session.save(st);
    	session.getTransaction().commit();
    	session.close();
    	
    }
}
