/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package hql;

import java.util.List;
import javax.persistence.Query;

//import java.util.Random;
import org.hibernate.Session;
import org.hibernate.SessionFactory;
import org.hibernate.cfg.Configuration;

public class Library {
    public static void main(String[] args) {
    	
    	Configuration con = new Configuration().configure().addAnnotatedClass(Student.class);
    	SessionFactory sf = con.buildSessionFactory();
    	Session session = sf.openSession();
    	session.beginTransaction();
    	
//  Saving data to database 
    	
//    	Random r = new Random();
//    	for(int i=1; i<=50; i++) {
//    		Student s = new Student();
//    		s.setStid(i);
//    		s.setSname("Name " +i);
//    		s.setMarks(r.nextInt(100));
//    		session.save(s);
//    	}

//Fetching Data with HQL
    	
//    	Query q = session.createQuery("from Student where stid=21");
//    	Student student = (Student) q.getSingleResult();
//    		System.out.println(student);
    	
//Fetching Data as Object using HQL
    	
//    	Query q = session.createQuery("select stid, sname, marks from Student where stid=32");
//    	Object[] student = (Object[]) q.getSingleResult();
//    	for(Object o : student) {
//    		System.out.println(o);
//    	}

//Fetching List of Object data using HQL
    	Query q = session.createQuery("select stid, sname, marks from Student");
    	List<Object[]> students = (List<Object[]>) q.getResultList();
    	for(Object[] student: students) {
    		System.out.println(student[0] + ":" + student[1] + ":" + student[2]);
    	}
    	session.getTransaction().commit();
    	session.close();
    }
}
