/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package mapping;

import org.hibernate.Session;
import org.hibernate.SessionFactory;
import org.hibernate.cfg.Configuration;

public class Library {
	public static void main(String[] args) {
		
		//OneToOne
		Laptop laptop = new Laptop();
		laptop.setLid(101);
		laptop.setLname("Dell");
		
		Student st = new Student();
		st.setSid(1);
		st.setSname("Hemang");
		//For OneToOne
		st.setLaptop(laptop); 	

//For ManyToOne & ManyToMany
		
		// st.getLaptop().add(laptop); 

//For ManyToMany
	
		// laptop.getStudent().add(st); 
		
		
		Configuration con = new Configuration().configure().addAnnotatedClass(Student.class).addAnnotatedClass(Laptop.class);
		SessionFactory sf = con.buildSessionFactory();
		Session session = sf.openSession();
		session.beginTransaction();
		session.save(laptop);	//For OneToOne
		session.save(st);
		System.out.println(laptop);
		System.out.println(st);
		session.getTransaction().commit();
		session.close();
		
	}
}
