/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package caching;


import org.hibernate.Session;
import org.hibernate.SessionFactory;
import org.hibernate.cfg.Configuration;

public class Library {
    public static void main(String[] args) {
    	Student st = null;
//    	st.setSt_id(1);
//    	st.setSt_name("Hemang");
    	
    	Configuration con = new Configuration().configure().addAnnotatedClass(Student.class);
    	SessionFactory sf = con.buildSessionFactory();
    	
//session1
    	Session session1 = sf.openSession();
    	session1.getTransaction().begin();
    	
//using default get method
    	st = (Student) session1.get(Student.class, 1);
//    	session1.save(st);		//For saving to database
    	System.out.println(st);
    	
    	session1.getTransaction().commit();
    	session1.close();
    	
//session2
    	Session session2 = sf.openSession();
    	session2.getTransaction().begin();
    	
//using default get method
    	st = (Student) session2.get(Student.class, 1);
//    	session2.save(st);
    	System.out.println(st);
    	
    	session2.getTransaction().commit();
    	session2.close();
    	
    	
    }
}
